version: '3.8'

services:
  app:
    container_name: app
    build: .
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: .env

  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    logging:
      driver: none
    restart: unless-stopped

volumes:
  postgres_data:
